version: '3.8'

services:

  frontend:

    build: ./frontend

    container_name: expense-pro-frontend

    restart: always

    ports:
      - "8082:80"

  backend:

    build: ./backend

    container_name: expense-pro-backend

    restart: always

    env_file:
      - .env

    ports:
      - "5002:5000"

    depends_on:
      - mongo

  mongo:

    image: mongo

    container_name: expense-pro-mongo

    restart: always

    ports:
      - "27018:27017"

    volumes:
      - expense-data:/data/db

volumes:

  expense-data: